lib/storex_web/router.ex
defmodule StorexWeb.Router do
  use StorexWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug StorexWeb.Plugs.Cart
    plug StorexWeb.Plugs.ItemsCount
    plug StorexWeb.Plugs.CurrentUser
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", StorexWeb do
    pipe_through :browser # Use the default browser stack

    get "/", BookController, :index

    resources "/books", BookController
    resources "/carts", CartController, singleton: true, only: [:show, :create, :delete]
    resources "/users", UserController, only: [:new, :create]
    resources "/sessions", SessionController, singleton: true, only: [:new, :create, :delete]
    resources "/checkout", CheckoutController, only: [:new, :create]
  end

  # Other scopes may use custom stacks.
  # scope "/api", StorexWeb do
  #   pipe_through :api
  # end
end

lib/storex_web/views/layout_view.ex
defmodule StorexWeb.LayoutView do
  use StorexWeb, :view

  def items_count(conn) do
    StorexWeb.Plugs.ItemsCount.get(conn)
  end
end

lib/storex_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Book store for independant writers">
    <meta name="author" content="Manuel Ospina">

    <title>Welcome to Storex!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">
      <header class="header">
        <nav role="navigation">
          <ul class="nav nav-pills pull-right">  
            <%= if @is_admin do %>  
              <li><%= link "New Book", to: book_path(@conn, :new) %></li>
            <% end %>  

            <%= if @current_user do %>  
              <li><%= @current_user.full_name %></li>
              <li><%= link "log out", to: session_path(@conn, :delete), method: :delete %></li>
            <% else %>      
              <li><%= link "sign up", to: user_path(@conn, :new) %></li>
              <li><%= link "sign in", to: session_path(@conn, :new) %></li>
            <% end %>  

            <%= if items_count(@conn) do %>
              <li>
                <%= link to: cart_path(@conn, :show) do %>  
                cart <span class="badge"><%= items_count(@conn) %></span>
                <% end %>
              </li>  
            <% end %>  
          </ul>
        </nav>
        <!-- span class="logo"></span -->
      </header>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>

  </body>
</html>